type: object
description: Configuration for MLFlow experiment tracking.
properties:
  name:
    type: string
    description: >
      Experiment name for MLFlow tracking.

      Either `name` or `id` must be provided, and only one of them can be provided.
      If `name` is provided, a new experiment will be created.
      If `id` is provided, the experiment will be reused.
    title: Name
  tags:
    type: array
    description: >
      Tags for the evaluation experiment.
    items:
      $ref: ./ExperimentTag.yaml
    maxItems: 20
    title: Tags
  artifact_location:
    type: string
    description: >
      Artifact location is the directory where the evaluation artifacts will be stored.
      If not provided, the default artifact location will be used by the MLFlow server.
    title: Artifact Location
  id:
    type: string
    description: >
      Experiment ID for MLFlow tracking.

      Either `name` or `id` must be provided, and only one of them can be provided.
      If `name` is provided, a new experiment will be created.
      If `id` is provided, the experiment will be reused.
    title: Experiment Id
additionalProperties: false
title: Experiment Config
