type: object
description: Evaluation provider (configuration and available benchmarks)
allOf:
  - type: object
    properties:
      id:
        type: string
        description: Provider ID
  - $ref: ./ProviderConfigInternal.yaml
