type: object
description: Evaluation provider (configuration and available benchmarks)
properties:
  name:
    type: string
    description: Provider name
  description:
    type: string
    description: Provider description
  benchmarks:
    type: array
    items:
      $ref: ./BenchmarkResource.yaml
    description: Benchmarks offered by this provider
