service:
  port: 8080
  # These will be elsewhere on a cluster and coherent with the pod spec
  ready_file: "/tmp/repo-ready"
  termination_file: "/tmp/termination-log"
# These are here so that the config can be loaded from the secrets directory when needed
secrets:
  dir: /tmp
  mappings:
    # db_password: database.password
# These are here so that the config can be loaded from the environment variables when needed
env_mappings:
  PORT: service.port
  DB_URL: database.url
  MLFLOW_TRACKING_URI: mlflow.tracking_uri
# Database configuration
database:
  driver: sqlite
  url: file::eval_hub:?mode=memory&cache=shared
  # driver: pgx
  # url: postgres://user@localhost:5432/eval_hub
# MLFlow configuration
mlflow:
  #tracking_uri: http://localhost:5000
# This is an example of how to enable instrumentation in a cluster
otel:
  enabled: true
  exporter_type: "otlp-grpc"
  exporter_endpoint: "localhost:4317"
  exporter_insecure: true
  # sampling_ratio: "1.0"
  enable_tracing: true
  # enable_metrics: true
  # enable_logs: true
prometheus:
  enabled: true
